### PR TITLE
Added my name and a career advice

### PR DESCRIPTION
**Pull request by shweta-srinivasan44**

### CODE REVIEW

**Comment by shweta-srinivasan44** [comment]
Done

**Comment by shweta-srinivasan44** [comment]
done

**Review by renana — CHANGES_REQUESTED** [review]
This change removes other contributors from the file. Please revert this change and add your name to the list of contributors in the right location (the list is mostly sorted alphabetically).

Same for the career advice.

Thanks,
Renana

**Comment by renana** [comment]
Thank you for fixing this. The updated pr is merge so I am closing this one.

**Pull request closed without merging**
